name: Deploy via SMB

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment (blue or green)'
        required: true
        default: 'blue'


jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'

      - name: Install dependencies
        run: npm install
      
      - name: Run unit tests
        run: npm test

  deploy:
    needs: test
    runs-on: self-hosted
    environment: production
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Map network drive and copy files
        shell: powershell
        env:
          SMB_USER: ${{ secrets.SMB_USER }}
          SMB_PASS: ${{ secrets.SMB_PASS }}
          TARGET_ENV: ${{ github.event.inputs.target_env || 'blue' }}
        run: |
          try {
            $targetPath = if ($env:TARGET_ENV -eq 'green') {
              "\\kamino.azurinfo.fr\webs\test xcopy\green"
            } else {
              "\\kamino.azurinfo.fr\webs\test xcopy\blue"
            }
            Write-Host "Mapping network drive..."
            net use Z: $targetPath /user:$env:SMB_USER $env:SMB_PASS

            Write-Host "Copying files..."
            xcopy "C:\Users\utilisateur\Documents\test xcopy\*" "Z:\" /E /Y /I

            Write-Host "Deployment completed successfully."
          }
          catch {
            Write-Error "An error occurred during deployment: $_"
            exit 1
          }
          finally {
            Write-Host "Cleaning up network drive..."
            net use Z: /delete /y
          }
